### PR TITLE
Update cclyzer++ to v0.3

### PR DESCRIPTION
**Pull request by langston-barrett**
Just to stay up-to-date.

See https://github.com/GaloisInc/cclyzerpp/releases/tag/v0.2

Tested against the regular test suite - the new `ntu-uaf` test failed, but I didn't see a difference when I compared the pointer analysis output line-for-line against the most recent and first commit of cczlyer++. @thinkmoore can you run the tests and see if they pass or fail for you?

### CODE REVIEW

**Comment by langston-barrett** [comment]
> Tested against the regular test suite - the new ntu-uaf test failed, but I didn't see a difference when I compared the pointer analysis output line-for-line against the most recent and first commit of cczlyer++. 

Whoops, found a bug in my comparison script. Making this a draft until I fix that and find out why the UAF test is failing.

**Comment by langston-barrett** [comment]
Actually, it looks like this is a problem on `main`: https://github.com/GaloisInc/MATE/issues/56

**Comment by langston-barrett** [comment]
This works after rebasing onto #57 and upgrading to cclyzer++ v0.3!

**Comment by thinkmoore** [comment]
Does this need further review here @langston-barrett ? Or in cclyzer++'s repo?

**Comment by langston-barrett** [comment]
@thinkmoore I'm happy with whatever level of review you deem suitable. From highest-level to lowest, you might consider looikng at:

- [The changelog](https://galoisinc.github.io/cclyzerpp/changelog.html)
- [The list of merged MRs](https://github.com/GaloisInc/cclyzerpp/pulls?q=is%3Apr+is%3Aclosed)
- [The list of commits and diff from the pinned commit to v0.3](https://github.com/GaloisInc/cclyzerpp/compare/e224763fd3024549be0599c48b0e7c29b58a5d25...v0.3)

**Comment by thinkmoore** [comment]
I looked through all of the changed files etc via the merged PR list. All look reasonable to me assuming cclyzer++ and MATE tests pass. One minor question: https://github.com/GaloisInc/cclyzerpp/pull/85 removes the subset and unification together build target---don't we use that for testing?

**Review by thinkmoore — APPROVED** [review]

**Pull request merged**
